dependencies:
- python=3.7.5
- pip=19.3.1
- pip:
    - black==19.10b0
    - flake8==3.7.9
    - mypy==0.761
    - tensorflow==2.1.0
    - tensorflow_hub==0.7.0
    - sanic==19.12.2
    - ipykernel==5.1.4
    - nb_black==1.0.7
    - matplotlib==3.1.3
    - seaborn==0.10.0
